---
title: Bryan Zhang Week 2A Write UP 
---
1. The way I learned about the efficient market hypothesis at UMD is that prices in financial markets fully represent all available information today, making it impossible to make an excess return. I think David Swensen would agree with this to some extent, but he would make the argument that not all markets (like private equity) have the same level of information avaiable to the different participants

2. Swensen and his team do have views on the direction of the economy, but their views influence their asset allocation decision and doesn’t influence their decision to make short term “trades” or investments within a specific asset class^[Yale University Investments Office: February 2015,” HBS Case 815124-PDF-ENG, revised
April 22, 2015]. The private equity market is illiquid compared to public equities due to the deal/transactional nature of the business, making market timing difficult 

3. Howie (Yale Investment Staff) said something along the lines that Yale would prefer to invest with managers that are “regional specialists”^[Yale University Investments Office: February 2015,” HBS Case 815124-PDF-ENG, revised
April 22, 2015] that can build strong networks and develop deeper insights compared to people that spread themselves thin. So I think that Swensen would choose to invest in a fund managed by energy industry experts because they are like "regional specialists"

4. This is referring to the allocation towards alternative investments during the financial crisis in 2008-2009. Allocations towards absolute return, private equity, and real estate were all negatively impacted by the meltdown in the housing market, blowing up the portfolios of different investment managers.^[Yale University Investments Office: February 2015,” HBS Case 815124-PDF-ENG, revised
April 22, 2015] If all of Yale’s investment managers portfolios blew up, then Yale would be in a bad spot. 

5. Yale didn’t get into much trouble during the financial crises. It had seperately managed accounts that were shielded from other investors pulling their money from funds which caused large sell offs at deep discounts.^[Yale University Investments Office: February 2015,” HBS Case 815124-PDF-ENG, revised
April 22, 2015] Yale's AAA credit rating helped it secure funding via commercial paper facilities and revolving lines of credit to cover any short term expenses.^[Yale University Investments Office: February 2015,” HBS Case 815124-PDF-ENG, revised
April 22, 2015]

6. I think that the goal of the endowment is to grow the assets as much as possible. A portion of their compensation should come from a percentage of the assets within the endowment (base salary) and the other portion should come as a bonus for positive returns. I think this is fair for both Swensen and his employees.

7. I think the size of Swensen’s staff is appropriate because each of the internal staff are very skilled and highly intelligent, coming straight from Yale University itself. If there were 200-300 people instead of the 20-30 people that work in the investment office, then there might be an opportunity to set up an internal private equity fund or explore attractive coinvestment opportunities that it currently disliked. If there were 2-3 people instead of 20-30 people, then the investment office might need to reduce the number of external managers so that the 2-3 investment staff won’t be overwhelmed with client meetings and performance monitoring. I think Swensen would have recommended smaller endowments to allocate more capital to liquid assets like public equities and US Government Treasuries. These small endowments may not have the “prestige” that Yale has to access top-tier investment managers within the alternatives space that can generate exceptional returns. Also, small endowments can manage liquidity risk better with public equities and bonds

8. Yes, and the performance gap is noted by Swensen, Takahasi, and Sullivan when defining the reasons why they continue to invest in private equity.^[Yale University Investments Office: February 2015,” HBS Case 815124-PDF-ENG, revised
April 22, 2015] Swensen claims that the “very best” venture capital firms do much better than everyone else.^[Yale University Investments Office: February 2015,” HBS Case 815124-PDF-ENG, revised
April 22, 2015] They have superior connections and talent that allows them to invest in early stage companies that can generate 100x returns compared to venture capital firms that have less access to early stage deals.

9. Nancy Zimmerman’s hedge fund is engaged in the exploitation of price discrepancies within the fixed income markets.^[Sabrina Willmer and Tom Moroney, “Boston hedge fund is largest in world run by a
woman,” Bloomberg News, February 04, 2016] Swensen said that her strategy places an “obsessive focus on risk” which is something he values within his investment program.^[Sabrina Willmer and Tom Moroney, “Boston hedge fund is largest in world run by a
woman,” Bloomberg News, February 04, 2016] I believe that Swensen invests with Zimmerman’s hedge fund because, unlike the way Private Equity Managers use financial engineering to restructure assets for a quick flip in a leveraged buyout scenario^[Yale University Investments Office: February 2015,” HBS Case 815124-PDF-ENG, revised
April 22, 201], Zimmerman uses financial engineering to capture “real value” within the fixed income markets. 




