---
title: Week 4A, Warren Buffett vs AIG
---

1. I think he has 2 different view points here, Buffett himself took action to help out Goldman Sachs as noted in his annual letter, bolstering confidence in financial instutions that he thinks are necessary for the health of the US economy. But on the other hand he does make a big note that most of the "bailouts" are really favoring the leadership teams/CEOs whose negligence caused financial problems for these banks in th first place. He claims that most of the bailouts have left the leadership of major banks (and other financial companies) "relatively unscathed".

2. Buffett and Warburg Pincus seem to both be active in the hands on management of companies. Both of their goals are to own great businesses that generate strong cash flows. But one key difference is how Warburg Pincus finances its purchasing of businesses, which rely heavily on leverage compared to Berkshires mostly cash transactions. Yale and AIG may face similar models when trying value positions mark to market. The reason behind this is that Yale engages with Private Equity and Hedge Fund managers which may not be completely transparent with their valuations, or the valuations of their holdings are just inherently difficult to value. Unlike AIG, I think Yale has a better risk mamangement platform for understanding the risks and valuations associated with different investment managers. 

3. I think that Berkshire Hathaway does make most of its money from its insurance business. But its important to note that the "profits" generated from underwriting insurance doesn't come solely from the premiums paid by the insured, but by the investment returns generated by the "float" accumulated over time. "float" is just a term used to describe all the money that an insurance company has to pay out any claims, this "float" is accumluated over time by having an excess of premiums compared to claims. Warren Buffett has charactized "float" as being "free money" for periods when inflows from insurance premiums exceed outflows from insurance claims. Coupled with investment returns on the "free money", Berkshire Hathaway has grown underwriting profit for 10+ years since the shareholder letter



4. It seems like Buffett thinks that AIG management should be held accountable for their actions. In the Financial Crisis Inquiry Report, it was noted that the CEO and a bunch of other upper level manager leaders at AIG were completely "oblivious" to the collateral requirement on its credit default swaps. Going back to question 1, Buffett made it clear in his annual report that most of the "bailouts" to financial institutions facvored the leadership teams, allowing them to continue to live a lavish lifestyle at the expense of their shareholders. 

5. I think so because Kashyan, Rajan, and Stein think that an effective way to reduce risk within the asset management is by reducing leverage and increasing equity or cash. Berkshire Hathaway's balance sheet contrasts AIG with the large amounts of cash and minimal "leverage". AIG's balance sheet is comprised of difficult to value derivative contracts that only increase risk for the firm.  


6. In Buffett's shareholder letter he wrote that the Black-Scholes model doesn't perform well for valuing options that have long term maturities. The reason he cited was becuase the model itself is dependent on historical volatility which is a reasonable input for valuing options with short-term maturities but isn't a good input for valuing options that mature in 50-100 years from now. I think that its difficult to use historical volatiltiy to predict stock prices even 10 years from now. 

