---
title: Week7A Extra Credit
author: Bryan Zhang
---

6. It seems to me that Fannie Mae and Freddie Mac are 2 hungry customers in an all you can eat FHA loan buffet. The FHA (Federal Housing Administration) is in the business of guarenteeing mortgages, kind of like how we saw earlier in the class when AIG was selling protection. Fannie Mae and Freddie Mac are both hungry customers for these FHA mortgages, and compete with each other in buying these mortgages from the loan originators (banks). Unlike banks that have reserve requirements, Fannie Mae and Freddie Mac can go on FHA mortgage shopping spree (they are backed by the government after all!). Still, Fannie Mae and Freddie Mac have capital and liquidity requirements to meet their obligations. These guys are different from banks because banks are the ones originating the loans, kind of like the chefs of the buffet. These chefs are rewarded for the amount of FHA loan they make, the more the better, and the buffet is able to keep running because there are always the 2 faithful customers Freddie Mac and Fannie Mae that will always buy whatever the chefs cook up! 

7. The FDIC is similar to AIG, they are both in the business of selling protection (insurance). The FDIC specializes in deposit insurance, meaning protecting peoples' cash thats parked in banks (or other depository instutitions). Just like AIG, the FDIC demands premiums for its protective services. ^[Brookings: https://www.brookings.edu/articles/how-does-deposit-insurance-work/#:~:text=The%20FDIC%20receives%20no%20appropriation,invested%20in%20U.S.%20government%20obligations.] What does the FDIC do with all these premiums? Unlike Warren Buffett, who is savvy enough to invest the "float" generated from GEICO in the equity market, the FDIC has a Deposit Insurance Fund that invests solely in US government debt. The FDIC isn't motivated by profit, they are motivated to keep their funds as secure and liquid as possible, so that when a crisis happens, they can be quick to step in.