---
title: Week 7A Bond Market Macro-Structure
author: Bryan Zhang
---

1. The US government is weighted more heavily towards the downside with very little on the upside. I think the US government portfolio purposely resembles the butt of a joke in order to bear the risk of US consumers and businesses with the goal of stimulating economic growth. The US government ending up guranteeing new and outstanding mortgages made to subprime borrowers which is an extremely risky portion of the US government portfolio. Also uncollaterized student loans made to people with little to no income is also risky for the government, but it still makes these loans to promote a strong housing market and a more productive workforce. The government itself doesn't have much equity in private corporations, and usually when the government does have equity, it's to prevent the institution from going under (Freddie Mac, AIG, Amtrak), not to speculate for profit. 

2. The largest soverigen wealth fund is Norwary's Pension Fund Global ($1 trillion AUM) ^[Thompson Reuters, https://fingfx.thomsonreuters.com/gfx/rngs/GULF-QATAR-QIA/010041PS3P9/index.html] which does come close to the amount of assets that the US government had alone within the credit space in 2010 ($1.5 trillion)^[Credit Policy As Fiscal Policy, https://www.brookings.edu/wp-content/uploads/2016/03/Lucas_Spring2016BPEA_FullPaper.pdf]. The mix of assets share little similarity though as most sovereign wealth funds are overweight equities and underweight bonds/fixed income. This contrasts the United States government where a majority of their investments are credit/debt related. 

3. I think SWFs have objectives that are more similar towards private pension funds more so than the US government. SWFs and private pensions share the same goal of providing some sort of income stream for its beneficiaries while the US government has an added responsibility of managing the entire economy (the financial health of households and businesses in the US). 

4. The Fed is similar to a hedge fund as both institutions have sophisticated traders and trading strategies. but I'd argue that the overall objective of hedge funds and the FED are very different. A hedge fund aims to make money, and a lot of it. The FED aims to maintain reasonable price growth, and achieve maximum employment. In order to do so, the Federal Open Market Committee (FOMC) is tasked to essentially "manipulate the market" to implement monetary policy. The FED also has a mafia of primary dealers that help it carry out its dirty work of buying and selling securities. 

5. TARP is similar to a private equity fund, especailly those that specialize in distressed investing as it allowed the government to make a substantial investment in AIG ^[https://home.treasury.gov/data/troubled-assets-relief-program/aig], a company that the US government believed was essential to the economy. The US government followed a similar "plant and harvest" model that private equity buyout firms make but the objectives are inherently different. The US government isn't in the business of profiting from carried interest or general partner fees, rather its purchase of AIG was to prevent an even greater collapse of the US economy. 